Eistbaren/client

README.md
Where should the Badge be placed?
=> Add Codacy Code Quality Badge 

.github/workflows/pushToServerRepo.yml
=> Workflow: Add workflow to push updates to the server repo

.github/workflows/build.yml, README.md
Remove the pages workflow and instead upload an artifact containing the build files.
=> Chore: Remove github pages workflow

src/data/api.ts, src/utils/ContextWrapper.tsx
=> Fix: Api config in production

.eslintrc.js, src/components/LocationDropdown.tsx, src/components/RestaurantMap.tsx, src/css/RestaurantMap.css, src/pages/SearchPage.tsx
=> Feat: Range selector🚀

src/components/ReservationTimeslotTimePicker.tsx, src/pages/Landingpage.tsx
=> Fix: Page crashing on invalid input

src/pages/PersonalData.tsx
Ich glaube das hier sollte als regex reichen.
Des erlaubt zwar irgendwelche weirden `%#232#@a23^#@$%.com` aber ich glaube des ist kein Problem.
Fixes #73
=> Fix: Email Regex fixes #73

src/components/QueryTimeslotTimePicker.tsx, src/components/RestaurantCard.tsx, src/data/Context.tsx, src/data/Query.tsx, src/data/index.ts, src/pages/Landingpage.tsx, src/pages/PersonalData.tsx, src/pages/ReservationDetails.tsx, src/pages/TableSelectionPage.tsx, src/utils/ContextWrapper.tsx
=> Chore: context cleanup

package-lock.json, package.json, src/css/ReservationDetails.css, src/data/Context.tsx, src/data/api.ts, src/pages/ReservationDetails.tsx, src/utils/ContextWrapper.tsx
Fixes #82 
Einfach neue Reservierung unter https://reservation-bear.de/api/ erstellen hier ein bsp für morgen 13 Uhr
```json
{
"tables": [
"069f72db-2157-43de-8e88-21661b518200"
],
"time": {
"from":1657362266,
"to": 1657365866
},
"userName": "test34",
"userEmail": "mariusdkm@gmail.com"
}
```
=> Feat: Reservation Details Page

src/components/RestaurantMap.tsx, src/css/RestaurantMap.css
=> fix: Map stuff

src/pages/TableSelectionPage.tsx
=> Feat: disable tables with not enough seats

src/components/LocationDropdown.tsx, src/components/TimeDatePeopleDropdown.tsx, src/pages/SearchPage.tsx
=> Revert to old layout

src/components/FloatingSidebar.tsx, src/components/ImprintModal.tsx, src/css/Landingpage.css, src/pages/Landingpage.tsx
=> Feat: Add imprint modal

src/pages/SearchPage.tsx
@LadnerJonas
Die Skeletons sind jetzt genauso groß wie die Karten selbst :)
Und bei der Suche hab ich ein bisschen die Performance verbessert.
=> Fix: more performant search input, better skeletons

src/components/RestaurantDetailsModal.tsx
=> Feat: Add google maps link

src/pages/PersonalData.tsx, src/pages/ReservationDetails.tsx
=> Fix: Contrast on Resertvation Details Page

src/data/Query.tsx, src/pages/Landingpage.tsx, src/pages/SearchPage.tsx, src/pages/TableSelectionPage.tsx, src/utils/ContextWrapper.tsx
Fixes #117 
See https://github.com/Eistbaren/server/issues/176
=> Fix: numberVisitors filter

src/pages/ReservationDetails.tsx
=> Feat: better confirmation dialog

src/pages/ReservationDetails.tsx
=> Fix: rename ics file to add to calendar

src/pages/PersonalData.tsx
=> Fix: add autofocus

src/components/QueryTimeslotTimePicker.tsx, src/css/Landingpage.css, src/pages/Landingpage.tsx, src/pages/TableSelectionPage.tsx, src/utils/ContextWrapper.tsx
=> 🪲 Fix: Catch times under 12h in the future

src/components/Header.tsx
=> 🏎 Feat: Add ability to navigate with header

.imgbotconfig
=> Add configuration for imgbot

src/components/QueryTimeslotTimePicker.tsx, src/pages/Landingpage.tsx, src/pages/TableSelectionPage.tsx
=> Fix: Timepicker error messages

src/components/QueryTimeslotTimePicker.tsx
=> Fix: Set seconds to 0
